/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/checkList/components/ActionButtons': RouteRecordInfo<'/checkList/components/ActionButtons', '/checkList/components/ActionButtons', Record<never, never>, Record<never, never>>,
    '/checkList/components/PageHeader': RouteRecordInfo<'/checkList/components/PageHeader', '/checkList/components/PageHeader', Record<never, never>, Record<never, never>>,
    '/checkList/components/TaskItem': RouteRecordInfo<'/checkList/components/TaskItem', '/checkList/components/TaskItem', Record<never, never>, Record<never, never>>,
    '/forgotPassword': RouteRecordInfo<'/forgotPassword', '/forgotPassword', Record<never, never>, Record<never, never>>,
    '/landingPage': RouteRecordInfo<'/landingPage', '/landingPage', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/sign': RouteRecordInfo<'/sign', '/sign', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/tasks/': RouteRecordInfo<'/tasks/', '/tasks', Record<never, never>, Record<never, never>>,
    '/tasks/components/ActionButtons': RouteRecordInfo<'/tasks/components/ActionButtons', '/tasks/components/ActionButtons', Record<never, never>, Record<never, never>>,
    '/tasks/components/TaskDialog': RouteRecordInfo<'/tasks/components/TaskDialog', '/tasks/components/TaskDialog', Record<never, never>, Record<never, never>>,
    '/tasks/components/TaskItem': RouteRecordInfo<'/tasks/components/TaskItem', '/tasks/components/TaskItem', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/trips/': RouteRecordInfo<'/trips/', '/trips', Record<never, never>, Record<never, never>>,
    '/trips/[id]': RouteRecordInfo<'/trips/[id]', '/trips/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/trips/addBlocks': RouteRecordInfo<'/trips/addBlocks', '/trips/addBlocks', Record<never, never>, Record<never, never>>,
    '/trips/checkPoint': RouteRecordInfo<'/trips/checkPoint', '/trips/checkPoint', Record<never, never>, Record<never, never>>,
    '/trips/components/AreaCard': RouteRecordInfo<'/trips/components/AreaCard', '/trips/components/AreaCard', Record<never, never>, Record<never, never>>,
    '/trips/components/SelectedAreaCard': RouteRecordInfo<'/trips/components/SelectedAreaCard', '/trips/components/SelectedAreaCard', Record<never, never>, Record<never, never>>,
    '/trips/components/TripCard': RouteRecordInfo<'/trips/components/TripCard', '/trips/components/TripCard', Record<never, never>, Record<never, never>>,
    '/trips/create': RouteRecordInfo<'/trips/create', '/trips/create', Record<never, never>, Record<never, never>>,
    '/varification': RouteRecordInfo<'/varification', '/varification', Record<never, never>, Record<never, never>>,
  }
}
